language: node_js
node_js: 6
install: npm install
script:
 - npm run lint
before_cache: npm prune
branches:
  only:
    - master
# force container based infra
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false
cache:
  directories:
    - node_modules
    - bower_modules
    - output
